apiVersion: carbon-aware-actions.kubernetes/dev
kind: CarbonAwareScaler
metadata:
 name: scaledown2
spec:
  kedaScaledObjectRef:
    name: httpj
  defaultMaxReplicaCount: 89 # when Carbon Intensiy is lower than 90 (lowest provided input)
  scalingRules:
    - carbonIntensity: 300  # if CarbonIntensity between 90 and 100 => set to MaxReplicaCount to 80
      allowedMaxReplicaCount: 84
    - carbonIntensity: 500
      allowedMaxReplicaCount: 79
    - carbonIntensity: 600
      allowedMaxReplicaCount: 44

