apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: httpj
  namespace: default
  labels:
    deploymentName: dummy
    name: dummy
    name2: dummy3444
    carbon-aware: yess
spec:
  pollingInterval: 10
  cooldownPeriod:   12
  maxReplicaCount: 137
  minReplicaCount: 3
  scaleTargetRef:
    name: dummy
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "4"
        url: "https://greenapimockyaya.azurewebsites.net/api/scalingMetricAPI"
        valueLocation: 'Metric'
  advanced:                                          # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: false
