apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cronjobtimeschedulers.carbon-aware-actions.kubernetes
spec:
  scope: Namespaced
  group: carbon-aware-actions.kubernetes
  names:
    kind: CronJobTimeScheduler
    plural: cronjobtimeschedulers
    singular: cronjobtimescheduler
    shortNames:
      - cronjobtimescheduler
      - cronjobtimeschedulers
  versions:
    - name: dev
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
