apiVersion: carbon-aware-actions.kubernetes/dev
kind: CronJobTimeScheduler
metadata:
 name: timeshiftcronjob
 namespace: default
spec:
  cronJobRef:
    name: hello
    labels: 
      titi : toto    
      tutu2 : tete    
  jobDuration: 1 # expressed in Hours
  jobEarliestStart: "18:00" # expressed in Hours:minutes (24h) ; 
  jobDeadline: "07:00" # deadline means job has finished by this time
  timezone: CET # for France / Paris
  location: FR # in ElectricityMap jargon : location = zone = country
