apiVersion: carbon-aware-actions.kubernetes/dev
kind: JobTimeScheduler
metadata:
 name: TimeShiftJobs
spec:
  jobRef:
    name: kubernetes-parallel-job2
    #labels: 
    #- <> # this version of demo does not take into account labels ; could be implemented to Time Shift Jobs at the namespace level

  jobDuration: 7 # expressed in Hours
  jobFinishedAt: "08:00" # expressed in Hours
