baseURL = 'https://azure.github.io/sustainability/'
languageCode = 'en-gb'
title = 'Building Sustainable Solutions on Azure'
theme = 'relearn'
author = 'Danny Wigg'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = [ "relearn-dark" ]
showVisitedLinks = true
collapsibleMenu = true