apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: carbonawarescalers.carbon-aware-actions.kubernetes
spec:
  scope: Cluster
  #scope: Namespaced
  group: carbon-aware-actions.kubernetes
  names:
    kind: CarbonAwareScaler
    plural: carbonawarescalers
    singular: carbonawarescaler
    shortNames:
      - cascaler
      - cascalers
  versions:
    - name: dev
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
