apiVersion: carbon-aware-actions.kubernetes/dev
kind: JobInterruptor
metadata:
 name: pausejobs
spec:
  jobRef:
    name: interrupted-job
    #labels: 
    #- <> # this version of demo does not take into account labels ; could be implemented to Pause Jobs at the namespace level

  pauseJobWhenCarbonIntensityAbove: 300 # when Carbon Intensiy is lower than 90 (lowest provided input)

