apiVersion: batch/v1
kind: Job
metadata:
  name: interrupted-job
  labels:
    jobgroup: jobexample
spec:
  completions: 6
  parallelism: 2
  template:
    metadata:
      name: interrupted-job
      labels:
        jobgroup: jobexample
    spec:
      containers:
      - name: c
        image: devopscube/kubernetes-job-demo:latest
        args: ["25"]
      restartPolicy: OnFailure
